pipeline {
    
    agent any 
    
    environment {
        IMAGE_TAG = "${BUILD_NUMBER}"
    }
    
    stages {
        
        stage('Checkout'){
           steps {
                checkout scmGit(branches: [[name: '*/main']], extensions: [], 
                userRemoteConfigs: [[url: 'https://github.com/adahmo/Jenkins-Zero-To-Hero.git']])
           }
        }

        stage('Build Docker'){
            steps{
                script{
                    sh '''
                    echo 'Buid Docker Image'
                    docker build -t adamumj/cicd-abi:${BUILD_NUMBER} .
                    '''
                }
            }
        }

        stage('Push the artifacts'){
           steps{
                script{
                    sh '''
                    echo 'Push to Repo'
                    docker push adamumj/cicd-abi:${BUILD_NUMBER}
                    '''
                }
            }
        }
        
        stage('Checkout K8S manifest SCM'){
            steps {
               checkout scmGit(branches: [[name: '*/main']], extensions: [], 
               userRemoteConfigs: [[url: 'https://github.com/adahmo/Jenkins-Zero-To-Hero.git']])
            }
        }
        
        stage('Update K8S manifest & push to Repo'){
            steps {
                script{
                    checkout scmGit(branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/adahmo/Jenkins-Zero-To-Hero.git']])
                        sh '''
                        cat deploy.yaml
                        sed -i '' "s/32/${BUILD_NUMBER}/g" deploy.yaml
                        cat deploy.yaml
                        git add deploy.yaml
                        git commit -m 'Updated the deploy yaml | Jenkins Pipeline'
                        git remote -v
                        https://github.com/adahmo/Jenkins-Zero-To-Hero.git HEAD:main
                        '''                        
                    }
                }
            }
        }
    }
}
